services:
    eloquent.manager:
        public: true
        class: Illuminate\Database\Capsule\Manager
        calls:
            - [addConnection, [{host: "%database_host%", driver: 'mysql', database: "%database_name%", username: "%database_user%", password: "%database_password%"}]]
